export const data = [
  {
    adult: false,
    gender: 1,
    id: 1373737,
    known_for: [
      {
        adult: false,
        backdrop_path: "/aAM3cQmYGjjLQ24m0F0RWfjKQ57.jpg",
        genre_ids: [27, 18, 9648],
        id: 530385,
        media_type: "movie",
        original_language: "en",
        original_title: "Midsommar",
        overview:
          "Several friends travel to Sweden to study as anthropologists a summer festival that is held every ninety years in the remote hometown of one of them. What begins as a dream vacation in a place where the sun never sets, gradually turns into a dark nightmare as the mysterious inhabitants invite them to participate in their disturbing festive activities.",
        poster_path: "/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
        release_date: "2019-07-03",
        title: "Midsommar",
        video: false,
        vote_average: 7.2,
        vote_count: 6090,
      },
      {
        adult: false,
        backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
        genre_ids: [28, 12, 878],
        id: 497698,
        media_type: "movie",
        original_language: "en",
        original_title: "Black Widow",
        overview:
          "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
        poster_path: "/kwB7d51AIcyzPOBOHLCEZJkmPhQ.jpg",
        release_date: "2021-07-07",
        title: "Black Widow",
        video: false,
        vote_average: 7.3,
        vote_count: 9198,
      },
      {
        adult: false,
        backdrop_path: "/lqxxwTRk0l7CubY6JkJdhnwJEkn.jpg",
        genre_ids: [18, 10749, 36],
        id: 331482,
        media_type: "movie",
        original_language: "en",
        original_title: "Little Women",
        overview:
          "Four sisters come of age in America in the aftermath of the Civil War.",
        poster_path: "/yn5ihODtZ7ofn8pDYfxCmxh8AXI.jpg",
        release_date: "2019-12-25",
        title: "Little Women",
        video: false,
        vote_average: 7.9,
        vote_count: 5643,
      },
    ],
    known_for_department: "Acting",
    name: "Florence Pugh",
    popularity: 114.897,
    profile_path: "/421cSReX2Fktldac8SyY2k0yLwY.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 90633,
    known_for: [
      {
        adult: false,
        backdrop_path: "/AaABt75ZzfMGrscUR2seabz4PEX.jpg",
        genre_ids: [28, 12, 14],
        id: 297762,
        media_type: "movie",
        original_language: "en",
        original_title: "Wonder Woman",
        overview:
          "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.",
        poster_path: "/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg",
        release_date: "2017-05-30",
        title: "Wonder Woman",
        video: false,
        vote_average: 7.2,
        vote_count: 18863,
      },
      {
        adult: false,
        backdrop_path: "/egg7KFi18TSQc1s24RMmR9i2zO6.jpg",
        genre_ids: [28, 12, 14],
        id: 464052,
        media_type: "movie",
        original_language: "en",
        original_title: "Wonder Woman 1984",
        overview:
          "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.",
        poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
        release_date: "2020-12-16",
        title: "Wonder Woman 1984",
        video: false,
        vote_average: 6.5,
        vote_count: 7774,
      },
      {
        adult: false,
        backdrop_path: "/5fX1oSGuYdKgwWmUTAN5MNSQGzr.jpg",
        genre_ids: [28, 12, 14],
        id: 209112,
        media_type: "movie",
        original_language: "en",
        original_title: "Batman v Superman: Dawn of Justice",
        overview:
          "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
        poster_path: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
        release_date: "2016-03-23",
        title: "Batman v Superman: Dawn of Justice",
        video: false,
        vote_average: 6,
        vote_count: 16995,
      },
    ],
    known_for_department: "Acting",
    name: "Gal Gadot",
    popularity: 106.999,
    profile_path: "/AbXKtWQwuDiwhoQLh34VRglwuBE.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 3194176,
    known_for: [
      {
        adult: false,
        backdrop_path: "/27bkw4o1zhjQAM4WIFQPohiph1X.jpg",
        genre_ids: [18, 53],
        id: 931599,
        media_type: "movie",
        original_language: "tl",
        original_title: "Silip Sa Apoy",
        overview:
          "Take a peek at the life of an unhappy housewife who finds passionate love from her neighbor and how their affair brings them closer to fire.",
        poster_path: "/9grG4PVppBWqKs2hrKMEr6j3RWS.jpg",
        release_date: "2022-01-28",
        title: "Silip Sa Apoy",
        video: false,
        vote_average: 6,
        vote_count: 26,
      },
      {
        adult: false,
        backdrop_path: "/ru5zAV1Ij6bQGedBkczqhiBmjzn.jpg",
        genre_ids: [18],
        id: 1029446,
        media_type: "movie",
        original_language: "tl",
        original_title: "Selina's Gold",
        overview:
          "Selina's father sells her to Tiago who makes her a sex slave. With the help of Domeng, Tiago's blind slave, she plans their way out of this living hell.",
        poster_path: "/4a0X2GKDmhhp1U2FUKtKY6uNQHL.jpg",
        release_date: "2022-10-28",
        title: "Selina's Gold",
        video: false,
        vote_average: 7.2,
        vote_count: 24,
      },
      {
        adult: false,
        backdrop_path: "/ougkufYSiruP8jrEHQanXN7DxRv.jpg",
        genre_ids: [18, 10749],
        id: 893694,
        media_type: "movie",
        original_language: "tl",
        original_title: "Eva",
        overview:
          "When Eva gets involved in a steamy threesome with a houseboy and her lady boss, she realizes she has to choose only one between them.",
        poster_path: "/bXZ3j3kQgCRZj7KD4Q5F9m5ABaQ.jpg",
        release_date: "2021-12-24",
        title: "Eva",
        video: false,
        vote_average: 5.7,
        vote_count: 10,
      },
    ],
    known_for_department: "Acting",
    name: "Angeli Khang",
    popularity: 100.36,
    profile_path: "/fpZfoK4ANjaRegAcAZkKVIj94kR.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 1269,
    known_for: [
      {
        adult: false,
        backdrop_path: "/i1oWUGVDNBhGBykcCRBlX326udb.jpg",
        genre_ids: [80, 18, 36, 53],
        id: 117,
        media_type: "movie",
        original_language: "en",
        original_title: "The Untouchables",
        overview:
          "Young Treasury Agent Eliot Ness arrives in Chicago and is determined to take down Al Capone, but it's not going to be easy because Capone has the police in his pocket. Ness meets Jim Malone, a veteran patrolman and probably the most honorable one on the force. He asks Malone to help him get Capone, but Malone warns him that if he goes after Capone, he is going to war.",
        poster_path: "/8BquGK22zCcsmBWiaIakaaPpSZb.jpg",
        release_date: "1987-06-03",
        title: "The Untouchables",
        video: false,
        vote_average: 7.8,
        vote_count: 5125,
      },
      {
        adult: false,
        backdrop_path: "/ifnRFDSlMdLFs9Xjem6WewM68GD.jpg",
        genre_ids: [12, 18, 37],
        id: 581,
        media_type: "movie",
        original_language: "en",
        original_title: "Dances with Wolves",
        overview:
          "Wounded Civil War soldier, John Dunbar tries to commit suicide—and becomes a hero instead. As a reward, he's assigned to his dream post, a remote junction on the Western frontier, and soon makes unlikely friends with the local Sioux tribe.",
        poster_path: "/cvaBVpS0GzKqBd63pFT8f1E8OKv.jpg",
        release_date: "1990-03-30",
        title: "Dances with Wolves",
        video: false,
        vote_average: 7.8,
        vote_count: 3789,
      },
      {
        adult: false,
        backdrop_path: "/hJleEkILmKzJsvzrU8o5d66jbPa.jpg",
        genre_ids: [12, 28, 878],
        id: 9804,
        media_type: "movie",
        original_language: "en",
        original_title: "Waterworld",
        overview:
          "In a futuristic world where the polar ice caps have melted and made Earth a liquid planet, a beautiful barmaid rescues a mutant seafarer from a floating island prison. They escape, along with her young charge, Enola, and sail off aboard his ship.",
        poster_path: "/f4Q6BKm1lv9u5xoffbIIwrOYf6z.jpg",
        release_date: "1995-07-28",
        title: "Waterworld",
        video: false,
        vote_average: 6.2,
        vote_count: 3303,
      },
    ],
    known_for_department: "Acting",
    name: "Kevin Costner",
    popularity: 100.095,
    profile_path: "/608blZipRDZkDpzp8VItB64qMaT.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 18897,
    known_for: [
      {
        adult: false,
        backdrop_path: "/9FrpAtF87VKblKkDEiIZzYgO40K.jpg",
        genre_ids: [28, 35, 80],
        id: 2109,
        media_type: "movie",
        original_language: "en",
        original_title: "Rush Hour",
        overview:
          "When Hong Kong Inspector Lee is summoned to Los Angeles to investigate a kidnapping, the FBI doesn't want any outside help and assigns cocky LAPD Detective James Carter to distract Lee from the case. Not content to watch the action from the sidelines, Lee and Carter form an unlikely partnership and investigate the case themselves.",
        poster_path: "/we7wOLVFgxhzLzUt0qNe50xdIQZ.jpg",
        release_date: "1998-09-18",
        title: "Rush Hour",
        video: false,
        vote_average: 7,
        vote_count: 4308,
      },
      {
        adult: false,
        backdrop_path: "/zzFTSEAZcLGSbGipQVflSNUqpij.jpg",
        genre_ids: [28, 35, 80],
        id: 5175,
        media_type: "movie",
        original_language: "en",
        original_title: "Rush Hour 2",
        overview:
          "It's vacation time for Carter as he finds himself alongside Lee in Hong Kong wishing for more excitement. While Carter wants to party and meet the ladies, Lee is out to track down a Triad gang lord who may be responsible for killing two men at the American Embassy. Things get complicated as the pair stumble onto a counterfeiting plot. The boys are soon up to their necks in fist fights and life-threatening situations. A trip back to the U.S. may provide the answers about the bombing, the counterfeiting, and the true allegiance of sexy customs agent Isabella.",
        poster_path: "/aBQf2vMiCINeVC9v6BGVYKXurTh.jpg",
        release_date: "2001-08-03",
        title: "Rush Hour 2",
        video: false,
        vote_average: 6.7,
        vote_count: 3638,
      },
      {
        adult: false,
        backdrop_path: "/ozsLB1HRCN6ZAmJN89pWtoiAwnb.jpg",
        genre_ids: [28, 35, 80],
        id: 5174,
        media_type: "movie",
        original_language: "en",
        original_title: "Rush Hour 3",
        overview:
          "After a botched assassination attempt, the mismatched duo finds themselves in Paris, struggling to retrieve a precious list of names, as the murderous crime syndicate's henchmen try their best to stop them. Once more, Lee and Carter must fight their way through dangerous gangsters; however, this time, the past has come back to haunt Lee. Will the boys get the job done once and for all?",
        poster_path: "/rZ7IxJlPhNNJ6Rn8z1rzsXuA70P.jpg",
        release_date: "2007-08-08",
        title: "Rush Hour 3",
        video: false,
        vote_average: 6.4,
        vote_count: 2861,
      },
    ],
    known_for_department: "Acting",
    name: "Jackie Chan",
    popularity: 99.056,
    profile_path: "/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 115440,
    known_for: [
      {
        backdrop_path: "/oKt4J3TFjWirVwBqoHyIvv5IImd.jpg",
        first_air_date: "2019-06-16",
        genre_ids: [18, 80],
        id: 85552,
        media_type: "tv",
        name: "Euphoria",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Euphoria",
        overview:
          "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.",
        poster_path: "/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
        vote_average: 8.4,
        vote_count: 8935,
      },
      {
        adult: false,
        backdrop_path: "/hJJfo9ktzsK88RU03wtyg9x7Yth.jpg",
        genre_ids: [53],
        id: 645710,
        media_type: "movie",
        original_language: "en",
        original_title: "The Voyeurs",
        overview:
          "When Pippa and Thomas move into their dream apartment, they notice that their windows look directly into the apartment opposite – inviting them to witness the volatile relationship of the attractive couple across the street. But what starts as a simple curiosity turns into full-blown obsession with increasingly dangerous consequences.",
        poster_path: "/8Y4XOIWhpOvSOEn8XrxbkH9yAXO.jpg",
        release_date: "2021-08-25",
        title: "The Voyeurs",
        video: false,
        vote_average: 6.6,
        vote_count: 671,
      },
      {
        adult: false,
        backdrop_path: "/xwgBHC2FgoIrQitl8jZwXXdsR9u.jpg",
        genre_ids: [35, 18, 53],
        id: 466272,
        media_type: "movie",
        original_language: "en",
        original_title: "Once Upon a Time… in Hollywood",
        overview:
          "Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…",
        poster_path: "/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
        release_date: "2019-07-24",
        title: "Once Upon a Time… in Hollywood",
        video: false,
        vote_average: 7.4,
        vote_count: 12107,
      },
    ],
    known_for_department: "Acting",
    name: "Sydney Sweeney",
    popularity: 97.433,
    profile_path: "/lwuFGAL8Vpy0seLgzJqhJcke3py.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 2275144,
    known_for: [
      {
        backdrop_path: "/sa9vB0xb3OMU6iSMkig8RBbdESq.jpg",
        first_air_date: "2023-07-23",
        genre_ids: [18],
        id: 113962,
        media_type: "tv",
        name: "Special Ops: Lioness",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Special Ops: Lioness",
        overview:
          "Cruz Manuelos, a rough-around-the-edges but passionate young Marine, is recruited to join the CIA’s Lioness Engagement Team to help bring down a terrorist organization from within. Joe, the station chief of the Lioness program, is tasked with training, managing and leading her female undercover operatives.",
        poster_path: "/rXCzevakJoAN1qnZY0nAQPSLVRv.jpg",
        vote_average: 8.3,
        vote_count: 192,
      },
      {
        backdrop_path: "/uQUHCqxHsG9blvtCoL7vluMG9Jp.jpg",
        first_air_date: "2021-12-19",
        genre_ids: [18, 37],
        id: 118357,
        media_type: "tv",
        name: "1883",
        origin_country: ["US"],
        original_language: "en",
        original_name: "1883",
        overview:
          "Follow the Dutton family as they embark on a journey west through the Great Plains toward the last bastion of untamed America. A stark retelling of Western expansion, and an intense study of one family fleeing poverty to seek a better future in America’s promised land — Montana.",
        poster_path: "/waLbm384SQDwLTCn6ttPqQS5kfV.jpg",
        vote_average: 8.4,
        vote_count: 390,
      },
      {
        adult: false,
        backdrop_path: "/efPIg8DJtfIqCqInzpIOIAOj1N5.jpg",
        genre_ids: [80, 18],
        id: 257406,
        media_type: "movie",
        original_language: "de",
        original_title: "Risse im Beton",
        overview:
          "Two men who do not know each other: Ertan, a 35-year-old ex-convict who is trying to make amends for his past actions, and Mikail, a teenager drug dealer and aspiring musician. However, both will have to face the same reality.",
        poster_path: "/iW9f50dzWh4co1aWh4utzzSwpqA.jpg",
        release_date: "2014-09-19",
        title: "Cracks in Concrete",
        video: false,
        vote_average: 5.9,
        vote_count: 4,
      },
    ],
    known_for_department: "Acting",
    name: "Stephanie Nur",
    popularity: 97.402,
    profile_path: "/rqn63IN10kstppQ9EnMExu8Ru6K.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 2037,
    known_for: [
      {
        backdrop_path: "/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
        first_air_date: "2013-09-12",
        genre_ids: [18, 80],
        id: 60574,
        media_type: "tv",
        name: "Peaky Blinders",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Peaky Blinders",
        overview:
          "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.",
        poster_path: "/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
        vote_average: 8.5,
        vote_count: 8724,
      },
      {
        adult: false,
        backdrop_path: "/veUl0QT8swshQ9Dz0fQ1k6ZkthD.jpg",
        genre_ids: [27, 53, 878],
        id: 170,
        media_type: "movie",
        original_language: "en",
        original_title: "28 Days Later",
        overview:
          "Twenty-eight days after a killer virus was accidentally unleashed from a British research facility, a small group of London survivors are caught in a desperate struggle to protect themselves from the infected. Carried by animals and humans, the virus turns those it infects into homicidal maniacs -- and it's absolutely impossible to contain.",
        poster_path: "/sQckQRt17VaWbo39GIu0TMOiszq.jpg",
        release_date: "2002-10-31",
        title: "28 Days Later",
        video: false,
        vote_average: 7.2,
        vote_count: 6038,
      },
      {
        adult: false,
        backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
        genre_ids: [28, 878, 12],
        id: 27205,
        media_type: "movie",
        original_language: "en",
        original_title: "Inception",
        overview:
          "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
        poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
        release_date: "2010-07-15",
        title: "Inception",
        video: false,
        vote_average: 8.4,
        vote_count: 34280,
      },
    ],
    known_for_department: "Acting",
    name: "Cillian Murphy",
    popularity: 96.371,
    profile_path: "/hGyB38HAtu0NcQaC7ijsfcQmDoE.jpg",
  },
];
